# Generated by Django 5.2.5 on 2025-09-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_image_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
